PUT http://localhost:8089/tsm/updateByPrimaryKeyw
Content-Type: application/json

{
  "mbookstorageId": 1
}

###

###
GET http://localhost:8089/tsm/selectAlls
Accept: application/json

###
PUT http://localhost:8089/redisboot/dept
Content-Type: application/json

{
  "deptno": 99,
  "dname": "vvvvvv",
  "loc": "kkkkkkk"
}

###
GET http://localhost:8089/tsm/enterprise/1
Accept: application/json

###
POST http://localhost:8089/tsm/addenterprise
Content-Type: application/json

{
  "deptno": 98,
  "dname": "乍和在肝可耕地",
  "loc": "uuuuuuuuu"
}

###
GET http://localhost:8089/tsm/selectAlls/1/2
Accept: application/json

###
